#Problem 44: Pentagonal numbers are generated by the formula, P<n>=n(3n-1)/2. The first 
#ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145. It can be seen that 
#P<4>+P<7>=P<8>. However, their difference, 70-22=48, is not pentagonal. Find the pair of 
#pentagonal numbers, P<j> and P<k>, for which their sum and difference are pentagonal and 
#D=|P<k>-P<j>| is minimised; what is the value of D?

pentagonals=[]
notFound=True
i=0
while notFound:
    i=i+1
    n=i*(3*i-1)/2
    pentagonals.append(int(n))
    i=i+1
    n=i*(3*i-1)/2
    pentagonals.append(int(n))
    num=pentagonals[int(i/2)]
    for j in range(0, int(i/2)):
        sum=num+pentagonals[j]
        if sum in pentagonals:
            print(num, "+", pentagonals[j], "=", sum)
            diff=num-pentagonals[j]
            if diff in pentagonals:
                pair=[num, pentagonals[j]]
                notFound=False
print("Found!", pair)
print("Difference:", pair[0]-pair[1])
