#Problem 45: Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
"""
Triangle    T<n>=n(n+1)/2   1,3,6,10,15,...
Pentagonal	P<n>=n(3n-1)/2  1,5,12,22,35,...
Hexagonal   H<n>=n(2n-1)    1,6,15,28,45,...
"""	
#It can be verified that T<285>=P<165>=H<143>=40755. Find the next triangle number that is also pentagonal and hexagonal.

#T=n(n+1)/2=(n^2+n)/2=n^2/2+n/2
#P=n(3n-1)/2=(3n^2-n)/2=3n^2/2-n/2
#H=n(2n-1)=(2n^2-n)=2n^2-n

#t_285=40755

def sqrt(num):
    return num**(1/2)

def invP(num):
    return sqrt(2/3*num+1/36)+1/6

def invH(num):
    return sqrt(t/2+1/16)+1/4

t=40755
i=285
print("Given Triangle Number:", t)

notFound=True
while notFound:
    i+=1
    t+=i
    Pn=invP(t)
    if Pn==int(Pn):
        Hn=invH(t)
        if Hn==int(Hn):
            print("Next Triangle Number:", t)
            notFound=False
